title: Nabbo
description: AI-enabled Family Logistics
url: "https://nabboapp.com"
baseurl: ""
theme: null
plugins: []

# Exclude non-website files from processing
exclude:
  - README.md

# Collections for knowledge base
collections:
  kb:
    output: true
    permalink: /kb/:title/

defaults:
  - scope:
      path: ""
      type: "kb"
    values:
      layout: "kb-article"
